# -- Ansible
ansible_master: { name: ansible-master, ip: 172.16.44.31 } #Change to your ansible master IP

# -- Security
#########################################################
########## WARNING: DO NOT SET THIS VARIABLE ############
from_scratch_cluster_installation: false
#########################################################  

# -- Admin
add_new_nodes: false



# -- General
username: ubuntu
path: "/home/ubuntu/"
path_system: /etc/systemd/system/
path_bin: /usr/bin/

# -- Common
consul_public_ip: "193.146.75.205" #This is the public IP of your consul server
consul_servers_ip: !unsafe ["193.146.75.205", "193.146.75.229", "193.146.75.143", "193.146.75.106"]                   #Add cluster servers IPs. Unsafe option avoids replacing double quotes with single quotes
my_ip: "{{ ansible_host }}"
environment_file: /etc/environment
hosts: /etc/hosts
new_certs: "new_site_certs" #This is the name of the folder where you have your new certificates
primary_datacenter: "ifca-ai4eosc"

# -- Volumes-docker
disks_path: /dev/
mount_dir: /mnt/data
docker_config: /etc/docker/
docker_registry: https://repo.ifca.es:5000
grub_path: /etc/default/grub

# -- Traefik
traefik_certs_dir: /etc/nomad.d/traefik-certs
traefik_certs: ifca-deployments.cloud.ai4eosc.eu #Change to your certs folder name
traefik_letsencrypt_email: admin@test.com

# -- Nomad
nomad_version: 1.10.2
nomad_data_dir: /opt/nomad
nomad: "{{ path_bin }}nomad"
nomad_config_dir: /etc/nomad.d
nomad_config: "{{ nomad_config_dir }}/"
nomad_certs_dir: "{{ nomad_config_dir }}/certs"
nomad_certs: "{{ nomad_certs_dir }}/"
nomad_fetched_dir: "{{ path }}{{consul_dc_name}}/nomad_fetched"
nomad_fetched: "{{ nomad_fetched_dir }}/"
nomad_ui_passwd: 1234
nomad_namespaces:
  - ai4eosc
  - imagine
  - tutorials
  - ai4life
nomad_nvidia_plugin_version: 1.0.0
gpu_plugin_dir: plugins
nomad_reserved_memory_mb: 4096
nomad_username: nomad
nomad_cni_version: 1.0.0
nomad_region: ai4os
nomad_client_meta: { "status": "test" }
docker_nvidia_driver_version: 550

# -- Consul
consul_version: 1.21.1
consul_data_dir: /opt/consul
consul: "{{ path_bin }}consul"
consul_config_dir: /etc/consul.d
consul_config: "{{ consul_config_dir }}/"
consul_certs_dir: "{{ consul_config_dir }}/certs"
consul_certs: "{{ consul_certs_dir }}/"
consul_fetched_dir: "{{ path }}{{consul_dc_name}}/consul_fetched"
consul_fetched: "{{ consul_fetched_dir }}/"
consul_dc_name: ifca-ai4eosc #Change to DC name
consul_policies_dir: "{{ consul_config }}policies"
consul_policies: "{{ consul_policies_dir }}/"
consul_username: consul
