# -- Ansible
ansible_master: { name: ansible-master, ip: 172.16.44.31 }

# -- Security
#########################################################
########## WARNING: DO NOT SET THIS VARIABLE ############
from_scratch_cluster_installation: true
#########################################################  

# -- Admin
add_new_nodes: false



# -- General
username: ubuntu
path: "/home/ubuntu/"
path_system: /etc/systemd/system/
path_bin: /usr/bin/

# -- Common
consul_public_ip: "193.146.75.205"                              #Add datacenter publics IP
consul_servers_ip: !unsafe ["193.146.75.205", "193.146.75.229", "193.146.75.143", "193.146.75.106"]                   #Add cluster servers IPs. Unsafe option avoids replacing double quotes with single quotes
my_ip: "{{ ansible_default_ipv4.address }}"
environment_file: /etc/environment
default_token: 11111111-1111-1111-1111-111111111111
default_management_token: 22222222-2222-2222-2222-222222222222
default_replication_token: 33333333-3333-3333-3333-333333333333
hosts: /etc/hosts
new_certs: "new_site_certs"
primary_datacenter: "ai4os-ifca"

# -- Volumes-docker
disks_path: /dev/
mount_dir: /mnt/data
docker_config: /etc/docker/
docker_registry: https://repo.ifca.es:5000
grub_path: /etc/default/grub

# -- Traefik
traefik_certs_dir: /etc/nomad.d/traefik-certs
traefik_certs: ifca-deployments.cloud.ai4eosc.eu

# -- Nomad
nomad_version: 1.7.3
nomad_data_dir: /opt/nomad
nomad: "{{ path_bin }}nomad"
nomad_config_dir: /etc/nomad.d
nomad_config: "{{ nomad_config_dir }}/"
nomad_certs_dir: "{{ nomad_config_dir }}/certs"
nomad_certs: "{{ nomad_certs_dir }}/"
nomad_fetched_dir: "{{ path }}{{consul_dc_name}}/nomad_fetched"
nomad_fetched: "{{ nomad_fetched_dir }}/"
nomad_ui_passwd: 1234
nomad_namespaces:
  - ai4eosc
  - imagine
  - tutorials
nomad_nvidia_plugin_version: 1.0.0
gpu_plugin_dir: plugins
nomad_reserved_memory_mb: 4096
nomad_username: nomad
nomad_cni_version: 1.0.0
nomad_region: ai4os

# -- Consul
consul_version: 1.17.1
consul_data_dir: /opt/consul
consul: "{{ path_bin }}consul"
consul_config_dir: /etc/consul.d
consul_config: "{{ consul_config_dir }}/"
consul_certs_dir: "{{ consul_config_dir }}/certs"
consul_certs: "{{ consul_certs_dir }}/"
consul_fetched_dir: "{{ path }}{{consul_dc_name}}/consul_fetched"
consul_fetched: "{{ consul_fetched_dir }}/"
consul_dc_name: ai4os-ifca                                      #Change to DC name
consul_policies_dir: "{{ consul_config }}policies"
consul_policies: "{{ consul_policies_dir }}/"
consul_username: consul
