# -- Ansible
ansible_master: { name: ansible1, ip: 172.16.40.39 }

# -- Security
#########################################################
########## WARNING: DO NOT SET THIS VARIABLE ############
from_scratch_cluster_installation: false
#########################################################  

# -- Admin
add_new_nodes: false



# -- General
path: /home/ubuntu/
path_system: /etc/systemd/system/
path_bin: /usr/bin/

# -- Common
consul_public_ip: "193.146.75.205" 
my_ip: "{{ hostvars[inventory_hostname]['ansible_host'] }}"
environment_file: /etc/environment
default_token: 12345678-1234-1234-1234-123456789ABC
hosts: /etc/hosts
new_certs: "new_site_certs"

# -- Volumes-docker
disks_path: /dev/
mount_dir: /mnt/data
docker_config: /etc/docker/
docker_registry: https://repo.ifca.es:5000
grub_path: /etc/default/grub

# -- Traefik
traefik_certs_dir: /etc/nomad.d/traefik-certs
traefik_certs: ifca-deployments.cloud.ai4eosc.eu

# -- Nomad
nomad_version: 1.7.2
nomad_data_dir: /opt/nomad
nomad: "{{ path_bin }}nomad"
nomad_config_dir: /etc/nomad.d
nomad_config: "{{ nomad_config_dir }}/"
nomad_certs_dir: "{{ nomad_config_dir }}/certs"
nomad_certs: "{{ nomad_certs_dir }}/"
nomad_fetched_dir: "{{ path }}nomad_fetched"
nomad_fetched: "{{ nomad_fetched_dir }}/"
nomad_ui_passwd: 1234
nomad_namespaces:
  - ai4eosc
  - imagine
  - tutorials
nomad_nvidia_plugin_version: 1.0.0
gpu_plugin_dir: plugins
nomad_reserved_memory_mb: 4096

# -- Consul
consul_version: 1.17.1
consul_data_dir: /opt/consul
consul: "{{ path_bin }}consul"
consul_config_dir: /etc/consul.d
consul_config: "{{ consul_config_dir }}/"
consul_certs_dir: "{{ consul_config_dir }}/certs"
consul_certs: "{{ consul_certs_dir }}/"
consul_fetched_dir: "{{ path }}consul_fetched"
consul_fetched: "{{ consul_fetched_dir }}/"
consul_dc_name: ai4os-consul
consul_policies_dir: "{{ consul_config }}policies"
consul_policies: "{{ consul_policies_dir }}/"
