- name: "Set agent token"
  shell: "{{ item }}"
  with_items:
    - sed -i 's/'{{ default_token }}'/'"$(sudo cat {{ consul_certs }}{{ inventory_hostname }}_consul_token | grep -oP 'SecretID:\s+\K\S+')"'/g' {{ consul_config }}server.hcl

