
- name: Asignar nombre a CPU clients
  set_fact:
    consul_hostname: "{{ consul_dc_name }}-wn-cpu-{{ groups['nomad_new_cpu_clients'].index(item) }}"
  with_items: "{{ groups['nomad_new_cpu_clients'] }}"
  when: item in groups['nomad_new_cpu_clients']
  debug:
    msg: "Nombre de host: {{ host_name }}"

- name: Asignar nombre a GPU clients
  set_fact:
    consul_hostname: "{{ consul_dc_name }}-wn-gpu-{{ groups['nomad_new_gpu_clients'].index(item) }}"
  with_items: "{{ groups['nomad_new_gpu_clients'] }}"
  when: item in groups['nomad_new_gpu_clients']
  debug:
    msg: "Nombre de host: {{ host_name }}"

- name: Asignar nombre a Traefik
  set_fact:
    consul_hostname: "{{ consul_dc_name }}-traefik"
  with_items: "{{ groups['traefik_new_master'] }}"
  when: item in groups['traefik_new_master']
  debug:
    msg: "Nombre de host: {{ host_name }}"

- name: "Copy consul.hcl configuration"
  template:
    src: templates/consul.j2
    dest: "{{ consul_config }}consul.hcl"
    owner: "{{ consul_username }}"
    force: no
  vars:
    server: False
    primary: True
  notify: Restart consul

- name: "Copy client.hcl configuration"
  template:
    src: templates/consul_client.j2
    dest: "{{ consul_config }}client.hcl"
    owner: "{{ consul_username }}"
    force: no
  notify: Restart consul
