
- name: "Copy consul.hcl configuration"
  template:
    src: templates/consul.j2
    dest: "{{ consul_config }}consul.hcl"
    owner: "{{ consul_username }}"
    # force: no
  vars:
    server: False
  notify: Restart consul

- name: "Copy client.hcl configuration"
  template:
    src: templates/consul_client.j2
    dest: "{{ consul_config }}client.hcl"
    owner: "{{ consul_username }}"
    # force: no
  notify: Restart consul
