## Set the node name based on the group

- name: Set CPU clients name
  set_fact:
    consul_hostname: "{{ consul_dc_name }}-wn-cpu-{{ groups['nomad_cpu_clients'].index(inventory_hostname) }}"
  when: ("nomad_cpu_clients" in groups and inventory_hostname in groups['nomad_cpu_clients'])

- name: Set GPU clients name
  set_fact:
    consul_hostname: "{{ consul_dc_name }}-wn-gpu-{{ groups['nomad_gpu_clients'].index(inventory_hostname) }}"
  when: ("nomad_gpu_clients" in groups and inventory_hostname in groups['nomad_gpu_clients'])

- name: Set Traefik name
  set_fact:
    consul_hostname: "{{ consul_dc_name }}-traefik"
  when: ("traefik_master" in groups and inventory_hostname in groups['traefik_master'])

- name: Set tryme name
  set_fact:
    consul_hostname: "{{ consul_dc_name }}-tn-cpu-{{ groups['nomad_tryme_clients'].index(inventory_hostname) }}"
  when: ("nomad_tryme_clients" in groups and inventory_hostname in groups['nomad_tryme_clients'])

- name: Set new CPU clients name
  set_fact:
    consul_hostname: "{{ consul_dc_name }}-wn-cpu-{{ groups['nomad_new_cpu_clients'].index(inventory_hostname) }}"
  when: ("nomad_new_cpu_clients" in groups and inventory_hostname in groups['nomad_new_cpu_clients'])

- name: Set new GPU clients name
  set_fact:
    consul_hostname: "{{ consul_dc_name }}-wn-gpu-{{ groups['nomad_new_gpu_clients'].index(inventory_hostname) }}"
  with_items: "{{ groups['nomad_new_gpu_clients'] }}"
  when: ("nomad_new_gpu_clients" in groups and inventory_hostname in groups['nomad_new_gpu_clients'])

- name:  Set new Traefik name
  set_fact:
    consul_hostname: "{{ consul_dc_name }}-traefik"
  when: ("traefik_new_master" in groups and inventory_hostname in groups['traefik_new_master'])

- name:  Set new TRY-ME client name
  set_fact:
    consul_hostname: "{{ consul_dc_name }}-tn-cpu-{{ groups['new_nomad_tryme_clients'].index(inventory_hostname) }}"
  when: ("new_nomad_tryme_clients" in groups and inventory_hostname in groups['new_nomad_tryme_clients'])

## Copy the client configuration file 

- name: "Copy consul.hcl configuration"
  template:
    src: templates/consul.j2
    dest: "{{ consul_config }}consul.hcl"
    owner: "{{ consul_username }}"
    force: no
  vars:
    server: False
    primary: True
  notify: Restart consul

- name: "Copy client.hcl configuration"
  template:
    src: templates/consul_client.j2
    dest: "{{ consul_config }}client.hcl"
    owner: "{{ consul_username }}"
    force: no
  notify: Restart consul
