
- name: "Copy consul.hcl configuration"
  template:
    src: templates/consul.j2
    dest: "{{ consul_config }}consul.hcl"
    owner: "{{ username }}"
  vars:
    server: False

- name: "Copy client.hcl configuration"
  template:
    src: templates/consul_client.j2
    dest: "{{ consul_config }}client.hcl"
    owner: "{{ username }}"
