- name: "Get consul server index"
  set_fact:
    server_index: "{{ lookup('ansible.utils.index_of', groups['consul_servers'], 'eq', inventory_hostname) }}"

- name: Wait Server certificate
  wait_for:
    path: "{{ consul_fetched }}{{ consul_dc_name }}-server-consul-{{ server_index }}.pem"
  delegate_to: localhost

- name: "Copy server certs from consul-master to consul-servers"
  copy:
    src: "{{ consul_fetched }}{{ consul_dc_name }}-server-consul-{{ server_index }}.pem"
    dest: "{{ consul_certs }}"

- name: Wait Server certificate key
  wait_for:
    path: "{{ consul_fetched }}{{ consul_dc_name }}-server-consul-{{ server_index }}-key.pem"
  delegate_to: localhost

- name: "Copy server keys from consul-master to consul-servers"
  copy:
    src: "{{ consul_fetched }}{{ consul_dc_name }}-server-consul-{{ server_index }}-key.pem"
    dest: "{{ consul_certs }}"

- name: "Export consul server cert"
  lineinfile:
    path: "{{ environment_file }}"
    line: "CONSUL_CLIENT_CERT={{ consul_certs }}{{ consul_dc_name }}-server-consul-{{ server_index }}.pem"
    regexp: "^CONSUL_CLIENT_CERT="

- name: "Export consul server cert"
  lineinfile:
    path: "{{ environment_file }}"
    line: "CONSUL_CLIENT_KEY={{ consul_certs }}{{ consul_dc_name }}-server-consul-{{ server_index }}-key.pem"
    regexp: "^CONSUL_CLIENT_KEY="
