- name: "Set certs storage path"
  set_fact:
    certs_path: "{{ consul_fetched }}"

- name: Wait CA certificate
  wait_for:
    path: "{{ consul_fetched }}consul-agent-ca.pem"
  delegate_to: localhost

- name: "Copy CA certificates from ansible master to consul hosts"
  copy:
   src: "{{ consul_fetched }}consul-agent-ca.pem"
   dest: "{{ consul_certs }}"
