- name: "Create consul_fetched dir in ansible_master if it does not exist"
  ansible.builtin.file:
    path: "{{ consul_fetched_dir }}"
    state: directory
    mode: '777'
  delegate_to: 127.0.0.1 

- name: "Fetch CA cert from consul-master to ansible-master"
  fetch:
    src: "{{ path }}consul-agent-ca.pem"
    dest: "{{ consul_fetched }}"
    flat: yes

- name: "Fetch consul-keygen from consul-master to ansible-master"
  fetch:
    src: "{{ path }}consul_keygen"
    dest: "{{ consul_fetched }}"
    flat: yes      

- name: "Fetch server certs from consul-master to ansible-master"
  fetch:
    src: "{{ path }}{{ consul_dc_name }}-server-consul-{{ item }}.pem"
    dest: "{{ consul_fetched }}"
    flat: yes
  loop: "{{ range(0, groups['consul_servers'] | length)|list }}"

- name: "Fetch server keys from consul-master to ansible-master"
  fetch:
    src: "{{ path }}{{ consul_dc_name }}-server-consul-{{ item }}-key.pem"
    dest: "{{ consul_fetched }}"
    flat: yes
  loop: "{{ range(0, groups['consul_servers'] | length)|list }}"






