- name: "Generate consul encryption key"
  shell: 
    cmd: consul keygen > {{ path }}consul_keygen
    creates: "{{ path }}consul_keygen"

- name: "Generate CA certificates"
  command:
    cmd: consul tls ca create
    chdir: "{{ path }}"
    creates: "{{ path }}consul-agent-ca.pem"

- name: "Generate certificate for each server"
  command:
    cmd: consul tls cert create -server -dc {{ consul_dc_name }} -domain consul
    chdir: "{{ path }}"
    creates: "{{ path }}{{ consul_dc_name }}-server-consul-{{ item }}.pem"
  loop: "{{ range(0, groups['consul_servers'] | length)|list }}"
