- name: Wait management Token
  wait_for:
    path: "{{ certs_path }}/consul_replication_token"
  delegate_to: localhost

- name: Get management Token
  set_fact:
    management_consul_token: "{{ lookup('file', certs_path + '/' + 'consul_bootstrap')| regex_search(regexp,'\\1') | first }}"
  vars:
    regexp: 'SecretID:\s+(.*)'
