- name: Wait ACL Token
  wait_for:
    path: "{{ certs_path }}/{{ consul_dc_name }}_consul_token"
  delegate_to: localhost

- name: Get ACL Token
  set_fact:
    agent_consul_token: "{{ lookup('file', certs_path + '/' + consul_dc_name + '_consul_token')| regex_search(regexp,'\\1') | first }}"
  vars:
    regexp: 'SecretID:\s+(.*)'
