---
# tasks file for consul_install

- block:
  - name: "Install packages"
    include_tasks: dependencies.yml

  - name: "Install consul"
    include_tasks: install.yml

  when: consul_install

# tasks file for consul_master

- block:
    
  - name: "Generate CA certificates"
    include_tasks: generate_ca_certificates.yml

  - name: "Fetch certificates to ansible master"
    include_tasks: fetch_certificates.yml

  when: consul_master

# tasks file for consul_common

- name: "Copy consul-agent-ca.pem"
  include_tasks: copy_ca_certificates.yml
  when: consul_common

# tasks file for consul_add_common

- name: "Copy consul certs, keys and tokens from zip"
  include_tasks: copy_new.yml
  when: consul_add_common

# tasks file for consul_client

- name: "Get encryption key from consul-keygen"
  set_fact:
    consul_keygen: "{{ lookup('file', '{{ consul_fetched }}consul_keygen') }}"
  when: consul_client or consul_add_client or consul_server or consul_add_server

- name: "Client configuration"
  include_tasks: configure_client.yml
  when: consul_client or consul_add_client

# tasks file for consul_server

- name: Configure consul server
  block:

  - name: "Copy server certificates"
    include_tasks: copy_server_certificates.yml

  - name: "Server configuration"
    include_tasks: configure_server.yml

  when: consul_server

# tasks file for consul_add_server

- name: Configure new consul server
  block:

  - name: "Copy server certificates"
    include_tasks: copy_new_certificates.yml

  - name: "Server configuration"
    include_tasks: configure_new_server.yml

  when: consul_add_server

- name: Start consul
  service:
    name: consul
    state: started

# tasks file for consul_acl

- name: Generating consul ACLs
  block:
  - name: "Create policies and token access"
    include_tasks: policies.yml
  when: consul_acl

# tasks file for consul_tokens_common

- name: "Get tokens"
  include_tasks: copy_tokens.yml
  when: consul_tokens_common

- name: "Set tokens"
  include_tasks: set_tokens.yml
  when: consul_tokens_common or consul_add_tokens_common

# tasks file for consul_tokens_server

- name: "Get acl tokens"
  include_tasks: get_acl_token.yml
  when: consul_tokens_server or consul_add_tokens_server or consul_tokens_client or consul_add_tokens_client

- name: "Set consul server tokens"
  include_tasks: set_server_tokens.yml
  when: consul_tokens_server or consul_add_tokens_server

# tasks file for consul_tokens_client

- name: "Set consul client tokens"
  include_tasks: set_client_tokens.yml
  when: consul_tokens_client or consul_add_tokens_client

