---
- name: "Install packages"
  include_tasks: dependencies.yml

- name: "Install consul"
  include_tasks: install.yml

- block:
    
  - name: "Generate CA certificates"
    include_tasks: generate_ca_certificates.yml

  - name: "Fetch certificates to ansible master"
    include_tasks: fetch_certificates.yml

  when: inventory_hostname in groups["consul_master"]

- name: "Copy consul-agent-ca.pem"
  include_tasks: copy_ca_certificates.yml

- name: "Copy consul certs, keys and tokens from zip"
  include_tasks: copy_new.yml
  when: inventory_hostname in groups["consul_new_clients"] or inventory_hostname in groups["consul_new_servers"]

- name: Wait consul_keygen
  wait_for:
    path: "{{ consul_fetched }}consul_keygen"
  delegate_to: localhost

- name: "Get encryption key from consul-keygen"
  set_fact:
    consul_keygen: "{{ lookup('file', '{{ consul_fetched }}consul_keygen') }}"

- name: "Client configuration"
  include_tasks: configure_client.yml
  when: inventory_hostname in groups["consul_clients"] or inventory_hostname in groups["consul_new_clients"]
  

- name: Configure consul server
  block:

  - name: "Copy server certificates"
    include_tasks: copy_server_certificates.yml

  - name: "Server configuration"
    include_tasks: configure_server.yml

  when: inventory_hostname in groups["consul_servers"]

- name: Configure new consul server
  block:

  - name: "Copy server certificates"
    include_tasks: copy_new_certificates.yml

  - name: "Server configuration"
    include_tasks: configure_new_server.yml

  when: inventory_hostname in groups["consul_new_servers"]

- name: Start consul
  service:
    name: consul
    state: started

- name: "Generating consul ACLs policies and token access"
  include_tasks: policies.yml
  when: inventory_hostname in groups["consul_master"]

- name: "Get tokens"
  include_tasks: copy_tokens.yml

- name: "Set tokens"
  include_tasks: set_tokens.yml

# tasks file for consul_tokens_server

- name: "Get acl tokens"
  include_tasks: get_acl_token.yml

- name: "Set consul server tokens"
  include_tasks: set_server_tokens.yml
  when: inventory_hostname in groups["consul_new_servers"] or inventory_hostname in groups["consul_servers"]

# tasks file for consul_tokens_client

- name: "Set consul client tokens"
  include_tasks: set_client_tokens.yml
  when: inventory_hostname in groups["consul_new_clients"] or inventory_hostname in groups["consul_clients"]

