- name: "Check if policies dir exists"
  stat:
    path: "{{ consul_policies_dir }}"
  register: consul_policies

- name: "Generate consul ACL bootstrap"
  shell:
    cmd: consul acl bootstrap > {{ path }}consul_bootstrap
    creates: "{{ path }}consul_bootstrap" 

- name: "Create policies dir if it does not exist"
  file:
    path: "{{ consul_policies_dir }}"
    state: directory

- name: "Get consul ACL token"
  set_fact:
    consul_token: "{{ lookup('file', path + 'consul_bootstrap')| regex_search(regexp,'\\1') | first }}"
  vars:
    regexp: 'SecretID:\s+(.*)'

- name: "Fetch consul ACL token from consul-master to ansible-master"
  fetch:
    src: "{{ path }}consul_bootstrap"
    dest: "{{ consul_fetched }}"
    flat: yes

- name: "Export consul token"
  lineinfile:
    path: "{{ environment_file }}"
    line: "export CONSUL_HTTP_TOKEN={{ consul_token.stdout }}"

- name: "Set exports"
  become: false
  shell: ". {{ environment_file }}"

- name: "Define consul policies"
  template:
    src: templates/consul_node_policy.j2
    dest: "{{ consul_policies_dir }}/node-policy.hcl"
    owner: "{{ username }}"

- name: "Create consul policies"
  shell: consul acl policy create -name node-policy -description "Consul Client Policy" -rules @"{{ consul_policies_dir }}/node-policy.hcl"
  when: not consul_policies.stat.exists

- name: "Generate token for each consul agent"
  shell: consul acl token create -policy-name node-policy -description "Consul Agent Token" -node-identity "{{ item }}:{{ consul_dc_name }}" > {{ item}}_consul_token
  loop: "{{ groups['consul'] }}" 
  when: not consul_policies.stat.exists

- name: "Fetch each consul agent token from consul-master to ansible-master"
  fetch:
    src: "{{ path }}{{ item }}_consul_token"
    dest: "{{ consul_fetched }}"
    flat: yes
  loop: "{{ groups['consul'] }}"
