- name: Wait consul_keygen
  wait_for:
    path: "{{ consul_fetched }}consul_keygen"
  delegate_to: localhost

- name: "Get encryption key from consul-keygen"
  set_fact:
    consul_keygen: "{{ lookup('file', '{{ consul_fetched }}consul_keygen') }}"
