- name: "Get consul ACL token from consul_master"
  set_fact:
    consul_token: "{{ lookup('file', certs_path + '/consul_bootstrap')| regex_search(regexp,'\\1') | first }}"
  vars:
    regexp: 'SecretID:\s+(.*)'

- name: "Export consul token"
  lineinfile:
    path: "{{ environment_file }}"
    line: "CONSUL_HTTP_TOKEN={{ consul_token }}"
    regexp: '^CONSUL_HTTP_TOKEN='

