- name: "Set consul token in server.hcl"
  replace:
    path: "{{ consul_config }}server.hcl"
    replace: "{{ agent_consul_token }}"
    regexp: '{{ default_token }}'
  notify: Restart consul

- name: "Set agent token"
  command: consul acl set-agent-token agent "{{ agent_consul_token }}"
  changed_when: false
  when: ("consul_servers" in groups and inventory_hostname in groups["consul_servers"])
