


 - name: Consul and Nomad new version installation
   hosts: version_update
   become: true
   roles:
       - { role: update_versions }

 - name: Consul restart
   hosts: version_update
   become: true
   tasks:
    - name: Restart consul
      service:
        name: consul
        state: restarted
      when: from_scratch_cluster_installation

 - name: Nomad restart
   hosts: version_update
   become: true
   roles:
   tasks:
    - name: Restart nomad
      service:
        name: nomad
        state: restarted

