 - name: Consul installation
   hosts: consul_new
   become: true
   roles:
     - { role: consul_install }

 - name: Consul common configuration
   hosts: consul_new
   become: true
   roles:
     - { role: consul_add_common }

 - name: Consul clients configuration
   hosts: consul_new_clients
   become: true
   roles: 
     - { role: consul_add_client }
      
 - name: Consul server configuration
   hosts: consul_new_servers 
   become: true
   roles:
     - { role: consul_add_server }
 
 - name: Start consul
   hosts: consul_new
   become: true
   tasks:
    - name: Start consul
      service:
        name: consul
        state: started
      when: from_scratch_cluster_installation

 - name: Restart consul
   hosts: consul_new
   become: true
   tasks:
    - name: Restart consul
      service:
        name: consul
        state: restarted
      when: from_scratch_cluster_installation

 - name: Get consul tokens
   hosts: consul_new
   become: true
   roles:
     - { role: consul_add_tokens_common }

 - name: Set server tokens
   hosts: consul_new_servers
   become: true
   roles:
     - { role: consul_add_tokens_server }

 - name: Set client tokens
   hosts: consul_new_clients
   become: true
   roles:
     - { role: consul_tokens_client }

 - name: Start consul
   hosts: consul_new
   become: true
   tasks:
    - name: Start consul
      service:
        name: consul
        state: started
      when: from_scratch_cluster_installation

 - name: Restart consul
   hosts: consul_new
   become: true
   tasks:
    - name: Restart consul
      service:
        name: consul
        state: restarted
      when: from_scratch_cluster_installation
