######## FROM SCRATCH CONSUL INSTALLATION ########
##################################################

 - name: Consul installation
   hosts: consul
   become: true
   pre_tasks:
     - name: Security check
       assert:
         that:
           - from_scratch_cluster_installation
         fail_msg: "ABORTING FROM-SCRATCH CONSUL INSTALLATION"
         success_msg: "INSTALLING CONSUL FROM SCRATCH"
   roles:
     - role: consul
       when:
         - from_scratch_cluster_installation
