######## FROM SCRATCH NOMAD INSTALLATION ########
##################################################

 - name: CAUTION WARNING
   hosts: nomad
   become: true
   tasks:
     - name: Security check
       assert:
         that:
           - from_scratch_cluster_installation
         fail_msg: "ABORTING FROM-SCRATCH NOMAD INSTALLATION"
         success_msg: "INSTALLING NOMAD FROM SCRATCH"

   roles:
     - role: nomad
       when:
         - from_scratch_cluster_installation
