######## FROM SCRATCH CONSUL INSTALLATION ########
##################################################

 - name: CAUTION WARNING
   hosts: consul
   tasks:
     - name: Security check
       assert:
         that:
           - from_scratch_cluster_installation
         fail_msg: "ABORTING FROM-SCRATCH CONSUL INSTALLATION"
         success_msg: "INSTALLING CONSUL FROM SCRATCH"

 - name: Consul installation
   hosts: consul
   become: true
   roles:
     - role: consul
       when: from_scratch_cluster_installation
       consul_install: true

 - name: Consul master configuration
   hosts: consul_master
   become: true
   roles:
     - role: consul
       when: from_scratch_cluster_installation
       consul_master: true

 - name: Consul common configuration
   hosts: consul
   become: true
   roles:
     - role: consul
       when: from_scratch_cluster_installation
       consul_common: true

 - name: Consul clients configuration
   hosts: consul_clients
   become: true
   roles: 
     - role: consul
       when: from_scratch_cluster_installation
       consul_client: true
      
 - name: Consul server configuration
   hosts: consul_servers 
   become: true
   roles: 
     - role: consul
       when: from_scratch_cluster_installation
       consul_server: true

 - name: Consul ACLs
   hosts: consul_master
   become: true
   roles: 
     - role: consul
       when: from_scratch_cluster_installation
       consul_acl: true

 - name: Get consul tokens
   hosts: consul
   become: true
   roles: 
     - role: consul
       when: from_scratch_cluster_installation
       consul_tokens_common: true

 - name: Set server tokens
   hosts: consul_servers
   roles: 
     - role: consul
       when: from_scratch_cluster_installation
       consul_tokens_server: true

 - name: Set client tokens
   hosts: consul_clients
   become: true
   roles: 
     - role: consul
       when: from_scratch_cluster_installation
       consul_tokens_client: true
