 - name: Consul installation
   hosts: consul_new
   become: true
   roles:
     - role: consul
   tags:
     - consul_install

 - name: Consul common configuration
   hosts: consul_new
   become: true
   roles:
     - role: consul
   tags:
     - consul_add_common

 - name: Consul clients configuration
   hosts: consul_new_clients
   become: true
   roles:
     - role: consul
   tags:
     - consul_add_client
      
 - name: Consul server configuration
   hosts: consul_new_servers 
   roles:
     - role: consul
   tags:
     - consul_add_server

 - name: Get consul tokens
   hosts: consul_new
   become: true
   roles:
     - role: consul
   tags:
     - consul_add_tokens_common

 - name: Set server tokens
   hosts: consul_new_servers
   become: true
   roles:
     - role: consul
   tags:
     - consul_add_tokens_server

 - name: Set client tokens
   hosts: consul_new_clients
   become: true
   roles: 
     - role: consul
   tags:
     - consul_tokens_client
