######## FROM SCRATCH CONSUL INSTALLATION ########
##################################################

 - name: Consul installation
   hosts: consul
   become: true
   pre_tasks:
     - name: Security check
       assert:
         that:
           - from_scratch_cluster_installation
         fail_msg: "ABORTING FROM-SCRATCH CONSUL INSTALLATION"
         success_msg: "INSTALLING CONSUL FROM SCRATCH"
   roles:
     - role: consul
       when: from_scratch_cluster_installation
       consul_install: true

     - role: consul
       when: inventory_hostname in groups["consul_master"]
       consul_certificates: true

     - role: consul
       consul_common: true

     - role: consul
       when: inventory_hostname in groups["consul_clients"]
       consul_client: true

     - role: consul
       when: inventory_hostname in groups["consul_servers"]
       consul_server: true

     - role: consul
       when: inventory_hostname in groups["consul_master"]
       consul_acl: true

     - role: consul
       consul_tokens_common: true

     - role: consul
       when: inventory_hostname in groups["consul_servers"]
       consul_tokens_server: true

     - role: consul
       when: inventory_hostname in groups["consul_clients"]
       consul_tokens_client: true
