 - name: Nomad installation
   hosts: nomad_new
   become: true
   roles:
     - { role: nomad_install }

 - name: Nvidia drivers
   hosts: nomad_new_gpu_clients
   become: true
   roles:
     - { role: nomad_nvidia }

 - name: Nomad common configuration
   hosts: nomad_new
   become: true
   roles:
     - { role: nomad_add_common }

 - name: Nomad cpu clients configuration
   hosts: nomad_new_cpu_clients
   become: true
   roles: 
     - { role: nomad_add_cpu_client }

 - name: Nomad gpu clients configuration
   hosts: nomad_new_gpu_clients
   become: true
   roles:
     - { role: nomad_add_gpu_client }

 - name: Nomad server configuration
   hosts: nomad_new_servers 
   become: true
   roles:
     - { role: nomad_add_server }

 - name: Get nomad tokens
   hosts: nomad_new
   become: true
   roles:
     - { role: nomad_add_tokens_common }

 - name: Set client tokens
   hosts: nomad_new_clients
   become: true
   roles:
     - { role: nomad_tokens_client }

 - name: Set server tokens
   hosts: nomad_new_servers
   become: true
   roles:
     - { role: nomad_tokens_server }

 - name: Start nomad
   hosts: nomad_new
   become: true
   roles:
     - { role: nomad_start }
     
 - name: Restart nomad
   hosts: nomad_new
   become: true
   roles:
     - { role: nomad_restart }

