######## FROM SCRATCH CONSUL INSTALLATION ########
##################################################

 - name: CAUTION WARNING
   hosts: consul
   tasks:
     - name: Security check
       assert:
         that:
           - from_scratch_cluster_installation
         fail_msg: "ABORTING FROM-SCRATCH CONSUL INSTALLATION"
         success_msg: "INSTALLING CONSUL FROM SCRATCH"

 - name: Consul installation
   hosts: consul
   become: true
   roles:
     - role: consul
       when: from_scratch_cluster_installation
   tags:
     - consul_install

 - name: Consul master configuration
   hosts: consul_master
   become: true
   roles:
     - role: consul
       when: from_scratch_cluster_installation
   tags:
     - consul_master

 - name: Consul common configuration
   hosts: consul
   become: true
   roles:
     - role: consul
       when: from_scratch_cluster_installation
   tags:
     - consul_common

 - name: Consul clients configuration
   hosts: consul_clients
   become: true
   roles: 
     - role: consul
       when: from_scratch_cluster_installation
   tags:
     - consul_client
      
 - name: Consul server configuration
   hosts: consul_servers 
   become: true
   roles: 
     - role: consul
       when: from_scratch_cluster_installation
   tags:
     - consul_server
 
  # This should be notified not executed directly
 - name: Restart consul
   hosts: consul
   become: true
   tasks:
    - name: Restart consul
      service:
        name: consul
        state: restarted
      when: from_scratch_cluster_installation

 - name: Start consul
   hosts: consul
   become: true
   tasks:
    - name: Start consul
      service:
        name: consul
        state: started
      when: from_scratch_cluster_installation

 - name: Consul ACLs
   hosts: consul_master
   become: true
   roles: 
     - role: consul
       when: from_scratch_cluster_installation
   tags:
     - consul_acl

 - name: Get consul tokens
   hosts: consul
   become: true
   roles: 
     - role: consul
       when: from_scratch_cluster_installation
   tags:
     - consul_tokens_common

 - name: Set server tokens
   hosts: consul_servers
   roles: 
     - role: consul
       when: from_scratch_cluster_installation
   tags:
     - consul_tokens_server

 - name: Set client tokens
   hosts: consul_clients
   become: true
   roles: 
     - role: consul
       when: from_scratch_cluster_installation
   tags:
     - consul_tokens_client

 # This should be notified not executed directly
 - name: Restart consul
   hosts: consul
   become: true
   tasks:
    - name: Restart consul
      service:
        name: consul
        state: restarted
      when: from_scratch_cluster_installation

 - name: Start consul
   hosts: consul
   become: true
   tasks:
    - name: Start consul
      service:
        name: consul
        state: started
      when: from_scratch_cluster_installation
