- name: "Copy server certs from consul-master to consul-servers"
  vars:
     server_index: "{{ ansible_play_batch.index(inventory_hostname) }}"
  copy:
    src: "{{ consul_fetched }}{{ consul_dc_name }}-server-consul-{{ server_index }}.pem"
    dest: "{{ consul_certs }}"

- name: "Copy server keys from consul-master to consul-servers"
  vars:
     server_index: "{{ ansible_play_batch.index(inventory_hostname) }}"
  copy:
    src: "{{ consul_fetched }}{{ consul_dc_name }}-server-consul-{{ server_index }}-key.pem"
    dest: "{{ consul_certs }}"

- name: "Get encryption key from consul-keygen"
  set_fact:
    consul_keygen: "{{ lookup('file', '{{ consul_fetched }}consul_keygen') }}"

      #- name: "Export server cert and key"
      #  vars:
      #    server_index: "{{ ansible_play_batch.index(inventory_hostname) }}"
      #  lineinfile:
      #    path: "{{ environment_file }}"
      #    line: "{{ item }}"
      #  with_items:
      #    - export CONSUL_CLIENT_CERT={{ consul_certs }}{{ consul_dc_name }}-server-consul-{{ server_index }}.pem
      #    - export CONSUL_CLIENT_KEY={{ consul_certs }}{{ consul_dc_name }}-server-consul-{{ server_index }}-key.pem  

- name: "Get consul server index"
  set_fact:
    server_index: "{{ ansible_play_batch.index(inventory_hostname) }}"

- name: "Export consul server cert"
  shell: "sed -i '/^{{ item }}/d; $ a\\{{ item }}{{ consul_certs }}{{ consul_dc_name }}-server-consul-{{ server_index }}.pem' {{ environment_file }}"
  with_items:
    - export CONSUL_CLIENT_CERT=

- name: "Export consul server key"
  shell: "sed -i '/^{{ item }}/d; $ a\\{{ item }}{{ consul_certs }}{{ consul_dc_name }}-server-consul-{{ server_index }}-key.pem' {{ environment_file }}"
  with_items:
    - export CONSUL_CLIENT_KEY=

- name: "Set exports"
  become: false
  shell: ". {{ environment_file }}"

