## Copy common configuration in new consul nodes

- name: "Copy consul.service configuration"
  template:
    src: templates/consul_service.j2
    dest: "{{ path_system }}consul.service"
    owner: ubuntu


