## Generate and copy consul certs and keys for new consul nodes

- name: "Generate certificate for each new consul server"
  command: consul tls cert create -server -dc {{ consul_dc_name }} -domain consul
  loop: "{{ groups['consul_new_servers'] }}"

- name: Find the newly created server certs and keys
  shell: "ls -t *.pem | head -n {{ groups['consul_new_servers'] | length * 2 }}"
  register: new_certs_and_keys
  changed_when: false

- name: Create new directory for new certs in ansible_master"
  ansible.builtin.file:
    path: "{{ path }}{{ new_certs }}"
    state: directory
    mode: '777'
  delegate_to: 127.0.0.1

- name: Copy the certs and keys to new directory
  ansible.posix.synchronize:
    src: "{{ item }}"
    dest: "{{ path }}{{ new_certs }}/"
    mode: pull
  with_items: "{{ new_certs_and_keys.stdout_lines }}"

- name: "Fetch CA cert from consul-master to ansible-master"
  fetch:
    src: "{{ path }}consul-agent-ca.pem"
    dest: "{{ path }}{{ new_certs }}/"
    flat: yes

