## Generate and copy consul tokens for new consul nodes

- name: "Generate token for new consul agents in {{ consul_dc_name }}"
  shell: consul acl token create -policy-name node-policy -description "Consul Agent Token" > {{ consul_dc_name }}_consul_token
  args:
    chdir: "{{ path }}"
    creates: "{{ path }}{{ consul_dc_name }}_consul_token"

- name: "Fetch new consul agent token from consul-master to ansible-master"
  fetch:
    src: "{{ path }}{{ consul_dc_name }}_consul_token"
    dest: "{{ path }}{{ new_certs }}/"
    flat: yes

# - name: "Fetch consul management token from consul-master to ansible-master"
#   fetch:
#     src: "{{ path }}consul_bootstrap"
#     dest: "{{ path }}{{ new_certs }}/"
#     flat: yes

- name: "Fetch consul replication token from consul-master to ansible-master"
  fetch:
    src: "{{ path }}consul_replication_token"
    dest: "{{ path }}{{ new_certs }}/"
    flat: yes

- name: "Fetch consul-keygen from consul-master to ansible-master"
  fetch:
    src: "{{ path }}consul_keygen"
    dest: "{{ path }}{{ new_certs }}/"
    flat: yes

