## Copy nomad certs and keys for new nomad nodes

- name: "Fetch CA cert, and client/server certs/keys from nomad-master to ansible-master"
  fetch:
    src: "{{ path }}{{ item }}.pem"
    dest: "{{ path }}{{ new_certs }}/{{ item }}.pem"
    flat: yes
  loop:
    - "nomad-agent-ca"
    - "global-client-nomad"
    - "global-client-nomad-key"
    - "global-server-nomad"
    - "global-server-nomad-key"
    - "global-cli-nomad"
    - "global-cli-nomad-key"


