## Zip directory with certs, keys and tokens for new nodes

- name: Zip
  community.general.archive:
    path: "{{ path }}{{ new_certs }}"
    dest: "{{ path }}{{ new_certs}}.zip"
  delegate_to: 127.0.0.1

