- name: "Export nomad addr"
  lineinfile:
    path: "{{ environment_file }}"
    line: "{{ item }}"
  with_items:
    - export NOMAD_ADDR=https://127.0.0.1:4646
    - export NOMAD_CACERT={{ nomad_certs }}nomad-ca.pem
    - export NOMAD_CLIENT_CERT={{ nomad_certs }}cli.pem
    - export NOMAD_CLIENT_KEY={{ nomad_certs }}cli-key.pem

- name: "Set exports"
  become: false
  shell: ". {{ environment_file }}"

- name: "Start nomad"
  command: "{{ item }}"
  with_items:
   - sudo systemctl stop nomad
   - sudo systemctl disable nomad
   - sudo systemctl enable nomad
   - sudo systemctl start nomad
  
