---
# tasks file for nomad_server

- name: Configure nomad server

  block:
  - name: "Copy server certificates"
    include_tasks: copy_certificates.yml

  - name: "Server configuration"
    include_tasks: configure.yml
