- name: Create gpu plugin dir if it does not exist (volume)"
  ansible.builtin.file:
    path: "{{ mount_dir }}/{{ gpu_plugin_dir }}"
    state: directory
    mode: '0755'
  when: inventory_hostname in groups["nomad_volume"]
    
- name: Create gpu plugin dir if it does not exist (not volume)"
  ansible.builtin.file:
    path: "{{ nomad_data_dir }}/{{ gpu_plugin_dir }}"
    state: directory
    mode: '0755'
  when: inventory_hostname not in groups["nomad_volume"]

- name: Extract nomad-device-nvidia package (volume)
  unarchive:
    src: "https://releases.hashicorp.com/nomad-device-nvidia/{{ nomad_nvidia_plugin_version }}/nomad-device-nvidia_{{ nomad_nvidia_plugin_version }}_linux_amd64.zip"
    dest: "{{ mount_dir }}/{{ gpu_plugin_dir }}"
    remote_src: yes
  when: inventory_hostname in groups["nomad_volume"]

- name: Extract nomad-device-nvidia package (not volume)
  unarchive:
    src: "https://releases.hashicorp.com/nomad-device-nvidia/{{ nomad_nvidia_plugin_version }}/nomad-device-nvidia_{{ nomad_nvidia_plugin_version }}_linux_amd64.zip"
    dest: "{{ nomad_data_dir }}/{{ gpu_plugin_dir }}"
    remote_src: yes
  when: inventory_hostname not in groups["nomad_volume"]

