- name: "Add swap limit capabilities"
  ansible.builtin.lineinfile:
    path: "{{ grub_path }}"
    regexp: '^GRUB_CMDLINE_LINUX='
    line: 'GRUB_CMDLINE_LINUX="cgroup_enable=memory swapaccount=1'
  register: line_changed

- name: "Update grub boot loader"
  shell: update-grub
  when: line_changed.changed
  
- name: "Reboot if line was changed"
  reboot: 
  when: line_changed.changed

