- name: "Copy client certificate"
  copy:
   src: "{{ new_certs }}/client.pem"
   dest: "{{ nomad_certs}}"

- name: "Copy client key certificate"
  copy:
   src: "{{ new_certs }}/client-key.pem"
   dest: "{{ nomad_certs }}"


