- name: "Check if consul certificate exists"
  stat:
   path: "{{ path }}consul-agent-ca.pem"
  register: stat_ca

- name: "Generate consul encryption key"
  shell: consul keygen > consul_keygen
  when: stat_ca.stat.exists == False

- name: "Generate CA certificates"
  shell: consul tls ca create
  when: stat_ca.stat.exists == False

- name: "Count server certificates"
  shell: grep -f "{{ consul_dc_name }}"-server-consul-* | wc -l
  register: server_count

- name: "Compute how many server certificates to generate"
  set_fact:
    difference: "{{ (groups['consul_servers'] | length | int) }}"

- name: "Generate certificate for each server"
  command: consul tls cert create -server -dc {{ consul_dc_name }} -domain consul
  with_sequence: "start=1 end={{ difference | int }}"
  when: difference | int > 0


