---
# tasks file for consul_master

- name: Generating consul certificates

  block:
  - name: "Generate"
    include_tasks: generate_certificates.yml

  - name: "Copy"
    include_tasks: copy_certificates.yml

