- name: "Copy client certificate"
  copy:
   src: "{{ nomad_fetched }}client.pem"
   dest: "{{ nomad_certs}}"

- name: "Copy client key certificate"
  copy:
   src: "{{ nomad_fetched }}client-key.pem"
   dest: "{{ nomad_certs }}"

