---
# tasks file for nomad_gpu_client

- name: Configure nomad GPU client

  block:
  - name: "Copy client certificates"
    include_tasks: copy_certificates.yml

  - name: "Client configuration"
    include_tasks: configure.yml

