# Configure Nomad clients
- name: Commit ID
  command: "git rev-parse HEAD"
  register: commit_id
  delegate_to: 127.0.0.1
  changed_when: false

- name: Real node hostname
  command: "hostname"
  register: real_hostname
  delegate_to: 127.0.0.1
  changed_when: false
    
- name: "Copy client.hcl configuration"
  template:
   src: templates/nomad_client.j2
   dest: "{{ nomad_config }}client.hcl"
   owner: "{{ nomad_username }}"
   force: no
  vars:
    commit_id_fact: "{{ commit_id.stdout }}"
    real_hostname_fact: "{{ real_hostname.stdout }}"
  notify:
    - Restart nomad
