# Configure Nomad clients

- name: "Copy client.hcl configuration"
  template:
   src: templates/nomad_client.j2
   dest: "{{ nomad_config }}client.hcl"
   owner: "{{ nomad_username }}"
   force: no
  notify:
    - Restart nomad
