- name: "Copy nomad.hcl configuration"
  template:
   src: templates/nomad.j2
   dest: "{{ nomad_config }}nomad.hcl"
   owner: ubuntu

- name: "Copy nomad.service configuration"
  template:
    src: templates/nomad_service.j2
    dest: "{{ path_system }}nomad.service"
    owner: ubuntu


