# Configure Nomad clients
- name: Commit ID
  command: "git rev-parse HEAD"
  args:
    chdir: "{{ roles_dir | default('.') }}"
  register: commit_id
  delegate_to: 127.0.0.1
  changed_when: False

- name: Set commit ID
  set_fact:
    commit_id_fact: "{{ commit_id.stdout }}"
    
- name: "Copy client.hcl configuration"
  template:
   src: templates/nomad_client.j2
   dest: "{{ nomad_config }}client.hcl"
   owner: "{{ nomad_username }}"
   force: no
  when: true
  
  notify:
    - Restart nomad
