- block:
  - name: "Get number of consul servers"
    shell: "consul members | grep server | wc -l"
    register: grep_result

  - name: "Set number of consul servers as a variable"
    set_fact:
      num_nomad_servers: "{{ grep_result.stdout | int }}"
  when: ("nomad_new_servers" in groups and inventory_hostname in groups["nomad_new_servers"])

- name: "Set number of consul servers as a variable"
  set_fact:
    num_nomad_servers: "{{ groups['nomad_servers'] | length }}"
  when: ("nomad_servers" in groups and inventory_hostname in groups["nomad_servers"])

- name: "Copy server.hcl configuration"
  template:
   src: templates/nomad_server.j2
   dest: "{{ nomad_config }}server.hcl"
   owner: "{{ nomad_username }}"
   force: no
  notify:
    - Restart nomad
