# Copy monitoring scripts for Nomad servers

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /opt/monitoring
    state: directory
    mode: '0755'

- name: Copy delete_trash script
  ansible.builtin.copy:
    src: delete_trash.sh
    dest: /opt/monitoring/delete_trash.sh
    owner: "{{ username }}"
    mode: '777'

- name: Copy delete_dead_jobs script
  ansible.builtin.copy:
    src: delete_dead_jobs.sh
    dest: /opt/monitoring/delete_dead_jobs.sh
    owner: "{{ username }}"
    mode: '777'

- name: Copy delete_pending_jobs script
  ansible.builtin.copy:
    src: delete_pending_jobs.sh
    dest: /opt/monitoring/delete_pending_jobs.sh
    owner: "{{ username }}"
    mode: '777'

- name: Add delete_trash to crontab
  ansible.builtin.cron:
    name: "Empty trash"
    special_time: daily
    job: "/opt/monitoring/delete_trash.sh"

#  - name: Add delete_dead_jobs to crontab"
#    ansible.builtin.cron:
#      name: "Remove dead jobs"
#      special_time: weekly
#      job: "/opt/monitoring/delete_dead_jobs.sh"

#  - name: Add delete_pending_jobs to crontab"
#    ansible.builtin.cron:
#      name: "Remove pending Jobs"
#      special_time: daily
#      job: "/opt/monitoring/delete_pending_jobs.sh"
