- name: "Copy server certificate"
  copy:
   src: "{{ nomad_fetched }}server.pem"
   dest: "{{ nomad_certs }}"

- name: "Copy server key certificate"
  copy:
   src: "{{ nomad_fetched }}server-key.pem"
   dest: "{{ nomad_certs }}"

