# Distribute certificates from ansible-master's {{new_certs}}.zip to each Nomad's agent
# ONLY in joining federation functionanility

## Copy consul certs, keys and tokens from zip file
- name: Wait Certificates Zip file
  wait_for:
    path: "{{ path }}{{ new_certs }}.zip"
  delegate_to: localhost

- name: "Unzip file in ansible_master if it is zipped"
  unarchive:
    src: "{{ path }}{{ new_certs }}.zip"
    dest: "{{ path }}"
    creates: "{{ path }}{{ new_certs }}/nomad-ca.pem"
  delegate_to: localhost
  run_once: true

# certs_path is set to {{new_certs}} to later know where to get the certs from (in each functionality)
- name: "Set certs storage path"
  set_fact:
    certs_path: "{{ path }}{{ new_certs }}/"

- name: "Copy CA certificates from ansible_master to nomad_hosts"
  copy:
   src: "{{ certs_path }}{{ item }}.pem"
   dest: "{{ nomad_certs }}"
  with_items:
    - nomad-ca
    - cli
    - cli-key
