- name: "Copy certificates from ansible_master to nomad_hosts"
  copy:
   src: "{{ certs_path }}{{ item }}.pem"
   dest: "{{ nomad_certs }}"
  with_items:
    - global-client-nomad
    - global-client-nomad-key
