- name: "Copy each nomad agent token from ansible_master to each nomad_host"
  copy:
   src: "{{ nomad_fetched }}/{{ inventory_hostname }}_nomad_token"
   dest: "{{ consul_certs }}"

- name: "Get agent token"
  set_fact:
    agent_nomad_token: "{{ lookup('file', nomad_fetched + inventory_hostname + '_nomad_token')| regex_search(regexp,'\\1') | first }}"
  vars:
    regexp: 'SecretID:\s+(.*)'