- name: "Set certs storage path"
  set_fact:
    certs_path: "{{ nomad_fetched }}"

- name: "Copy CA certificates from ansible_master to nomad_hosts"
  copy:
   src: "{{ nomad_fetched }}{{ item }}.pem"
   dest: "{{ nomad_certs }}"
  with_items:
    - nomad-agent-ca
    - global-cli-nomad
    - global-cli-nomad-key
