# Fetching certificates from nomad-master (where they were generated) to ansible-master's {{nomad_fetched}} dir (from where they will be distributed to the rest of the nodes)
# ONLY in from-scratch cluster deployment functionanility

- name: "Create nomad_fetched dir in ansible_master if it does not exist"
  file:
    path: "{{ nomad_fetched_dir }}"
    state: directory
    mode: '777'
    owner: "{{ username }}"
  delegate_to: localhost

- name: "Fetch CA cert, and client/server certs/keys from nomad-master to ansible-master"
  fetch:
    src: "{{ path }}{{ item }}.pem"
    dest: "{{ nomad_fetched }}{{ item }}.pem"
    flat: yes
  loop:
    - "nomad-ca"
    - "client"
    - "client-key"
    - "server"
    - "server-key"
    - "cli"
    - "cli-key"





