- name: "Create nomad_fetched dir in ansible_master if it does not exist"
  file:
    path: "{{ nomad_fetched_dir }}"
    state: directory
    mode: '775'
  delegate_to: localhost

- name: "Fetch CA cert, and client/server certs/keys from nomad-master to ansible-master"
  fetch:
    src: "{{ path }}{{ item }}.pem"
    dest: "{{ nomad_fetched }}{{ item }}.pem"
    flat: yes
  loop:
    - "nomad-ca"
    - "client"
    - "client-key"
    - "server"
    - "server-key"
    - "cli"
    - "cli-key"





