
- name: Create Nomad TLS CA
  command: nomad tls ca create -days=3650
  args:
    chdir: "{{ path }}"
    creates: "{{ path }}nomad-agent-ca.pem"

- name: Create Nomad TLS Server Cert
  command: nomad tls cert create -server -days=3650 -additional-dnsname={{ inventory_hostname }} -additional-dnsname=server.{{ consul_dc_name }}.nomad -ca {{ path }}nomad-agent-ca.pem -key {{ path }}nomad-agent-ca-key.pem
  args:
    chdir: "{{ path }}"
    creates: "{{ path }}global-server-nomad.pem"

- name: Create Nomad TLS client Cert
  command: nomad tls cert create -client -days=3650 -additional-dnsname={{ inventory_hostname }} -additional-dnsname=server.{{ consul_dc_name }}.nomad -ca {{ path }}nomad-agent-ca.pem -key {{ path }}nomad-agent-ca-key.pem
  args:
    chdir: "{{ path }}"
    creates: "{{ path }}global-client-nomad.pem"

- name: Create Nomad TLS CLI Cert
  command: nomad tls cert create -cli -days=3650
  args:
    chdir: "{{ path }}"
    creates: "{{ path }}global-cli-nomad.pem"

- name: "Export nomad addr"
  lineinfile:
    path: "{{ environment_file }}"
    line: "{{ item }}"
  with_items:
    - export NOMAD_ADDR=https://127.0.0.1:4646
    - export NOMAD_CACERT={{ nomad_certs }}nomad-agent-ca.pem
    - export NOMAD_CLIENT_CERT={{ nomad_certs }}global-cli-nomad.pem
    - export NOMAD_CLIENT_KEY={{ nomad_certs }}global-cli-nomad-key.pem

- name: "Set exports"
  become: false
  shell: ". {{ environment_file }}"
  changed_when: false

- name: "Generate web browser certificate for nomad's UI"
  shell: "openssl pkcs12 -export -inkey ./global-cli-nomad-key.pem -in ./global-cli-nomad.pem -out ./cli.p12 -passout pass:{{ nomad_ui_passwd }} -passin pass:{{ nomad_ui_passwd }}"
  args:
    chdir: "{{ path }}"
    creates: "{{ path }}cli.p12"

- name: "Create zip with nomad's UI certificate"
  community.general.archive:
    path:
      - cli.p12
      - global-cli-nomad.pem
      - global-cli-nomad-key.pem
      - nomad-agent-ca.pem
    dest: "{{ consul_dc_name }}.zip"
    format: zip
