- name: "Download Nomad binary"
  get_url:
   url: "https://releases.hashicorp.com/nomad/{{ nomad_version }}/nomad_{{ nomad_version }}_linux_amd64.zip"
   dest: "{{ path }}nomad_{{ nomad_version }}_linux_amd64.zip"
   force: no

- name: "Unzip nomad file"
  unarchive:
   src: "{{ path }}nomad_{{ nomad_version }}_linux_amd64.zip"
   dest: "{{ path_bin }}"
   remote_src: yes

- name: "Create nomad certs and data dir"
  file:
   path: "{{ item }}"
   state: directory
   mode: 0755
  loop:
   - "{{ nomad_certs_dir }}"
   - "{{ nomad_data_dir }}"

- name: "Create nomad user"
  user:
   name: "{{ nomad_username }}"
   shell: /bin/false
   system: yes
   home: "{{ nomad_config_dir }}"

- name: "Configure autocomplete-install"
  command: "{{ nomad }} -autocomplete-install"
  args:
   chdir: "{{ path_bin }}"
  changed_when: False
  ignore_errors: True

- name: "Copy nomad.service configuration"
  template:
    src: templates/nomad_service.j2
    dest: "{{ path_system }}nomad.service"
  notify:
    - systemctl daemon-reload
    - Restart nomad

