- name: Create gpu plugin dir if it does not exist"
  ansible.builtin.file:
    path: "{{ nomad_data_dir }}/{{ gpu_plugin_dir }}"
    state: directory
    mode: '0755'

- name: Extract nomad-device-nvidia package
  unarchive:
    src: "https://releases.hashicorp.com/nomad-device-nvidia/{{ nomad_nvidia_plugin_version }}/nomad-device-nvidia_{{ nomad_nvidia_plugin_version }}_linux_amd64.zip"
    dest: "{{ nomad_data_dir }}/"
    remote_src: yes
