- name: "Set agent token"
  shell: sed -i 's/'{{ default_token }}'/'"$(sudo cat {{ consul_certs }}{{ inventory_hostname }}_nomad_token | grep -oP 'SecretID:\s+\K\S+')"'/g' {{ nomad_config }}client.hcl

