# Change {{defaul_token}} to each agent's token {{agent_nomad_token}} in the Nomad servers files


- name: "Set consul token on server.hcl"
  replace:
    path: "{{ nomad_config }}server.hcl"
    replace: "{{ agent_nomad_token }}"
    regexp: '{{ default_token }}'
  notify: Restart nomad