- name: "Copy traefik token from ansible_master to traefik_master"
  copy:
   src: "{{ consul_fetched }}traefik_token"
   dest: "{{ consul_certs }}"

- name: "Create traefik SSL certs directory in ansible_master if it does not exist"
  ansible.builtin.file:
    path: "{{ path }}{{ traefik_certs }}"
    state: directory
    mode: '0755'
  delegate_to: 127.0.0.1

- name: "Unzip file in ansible_master if it is zipped"
  ansible.builtin.unarchive:
    src: "{{ path }}{{ traefik_certs }}.zip"
    dest: "{{ path }}"
    creates: "{{ path }}{{ traefik_certs }}/domain.pem"
  delegate_to: 127.0.0.1

- name: "Create traefik SSL certs directory in traefik_master if it does not exist"
  ansible.builtin.file:
    path: "{{ traefik_certs_dir }}"
    state: directory
    mode: '0755'

- name: "Copy traefik SSL certificates from ansible_master to trafik_master"
  copy:
   src: "{{ path }}{{ traefik_certs }}/{{ item }}"
   dest: "{{ traefik_certs_dir }}"
  with_items: 
    - domain.key
    - domain.pem

- name: "Define job config for traefik service"
  template:
    src: templates/{{ item }}.j2
    dest: "{{ path}}{{ item }}-{{ nomad_dc }}.hcl"
    owner: ubuntu
  with_items:
    - traefik

- name: "Set traefik token"
  shell: "{{ item }}"
  with_items:
    - sed -i 's/'{{ default_token }}'/'"$(sudo cat {{ consul_certs }}traefik_token | grep -oP 'SecretID:\s+\K\S+')"'/g' {{ path }}traefik-{{ hostvars[inventory_hostname]['nomad_dc'] }}.hcl

- name: "Plan and run service job"
  shell: "{{ item }}"
  with_items:
    - nomad job plan traefik-{{ nomad_dc }}.hcl
    - nomad job run traefik-{{ nomad_dc }}.hcl
  ignore_errors: true
