# Configure Traefik service for from-scratch deployment functionality

- set_fact:
    certs_dir: "{{ consul_fetched }}"

- set_fact:
    certs_dir: "{{ path }}{{ new_certs }}/"
  when: ("traefik_new_master" in groups and inventory_hostname in groups["traefik_new_master"])

# Copy Nomad's Traefik token from ansible-master's {{certs_dir}} dir to the Traefik node's dir.
- name: "Copy traefik token from ansible_master to traefik_master"
  copy:
   src: "{{ certs_dir }}traefik_token"
   dest: "{{ consul_certs }}"

# Unzip Traefik SSL certs from {{traefik_certs}}.zip to {{traefik_certs}} dir in ansible-master
- name: "Create traefik SSL certs directory in ansible_master if it does not exist"
  ansible.builtin.file:
    path: "{{ path }}{{ traefik_certs }}"
    state: directory
    mode: '0755'
  delegate_to: 127.0.0.1

- name: "Unzip file in ansible_master if it is zipped"
  ansible.builtin.unarchive:
    src: "{{ path }}{{ traefik_certs }}.zip"
    dest: "{{ path }}"
    creates: "{{ path }}{{ traefik_certs }}/domain.pem"
  delegate_to: 127.0.0.1

# Copy Traefik SSL certs from {{traefik_certs}} dir in ansible-master to the Traefik node's dir.
- name: "Create traefik SSL certs directory in traefik_master if it does not exist"
  ansible.builtin.file:
    path: "{{ traefik_certs_dir }}"
    state: directory
    mode: '0755'

- name: "Copy traefik SSL certificates from ansible_master to trafik_master"
  copy:
   src: "{{ path }}{{ traefik_certs }}/{{ item }}"
   dest: "{{ traefik_certs_dir }}"
  with_items:
    - domain.key
    - domain.pem

# Set Traefik token in the service job
- name: Get traefik Token
  set_fact:
    traefik_consul_token: "{{ lookup('file', certs_dir + 'traefik_token')| regex_search(regexp,'\\1') | first }}"
  vars:
    regexp: 'SecretID:\s+(.*)'

# Define Traefik service job
- name: "Define job config for traefik service"
  template:
    src: templates/traefik.j2
    dest: "{{ path }}traefik-{{ nomad_dc }}.hcl"
    owner: "{{ username }}"
  register: create_traefik_job_config

# Run the Traefik service job
- name: "Run service job"
  command: nomad job run traefik-{{ nomad_dc }}.hcl
  args:
    chdir: "{{ path }}"
  when: create_traefik_job_config is changed
