- name: "Install parted tool"
  ansible.builtin.package:
   name:
     - parted
   update_cache: yes

- name: "Chec if disk volume is unpartitioned"
  parted:
    device: "{{ disks_path }}{{ vol_name }}"
    state: info
  register: vol_info

- name: "Partition disk volume if unpartitioned"
  parted:
    device: "{{ disks_path }}{{ vol_name }}"
    number: 1
    state: present
    part_type: primary
    label: gpt
    align: optimal
    fs_type: ext4
    part_end: "100%"
    part_start: "0%"
    name: "{{ partition_name }}"
  when: vol_info.partitions | length == 0

- name: "Create filesystem on partition"
  filesystem:
    fstype: xfs
    dev: "{{ disks_path }}{{ vol_name }}"
    force: false
  register: format

- name: "Create mounting dir"
  file:
    path: "{{mount_dir}}"
    state: directory

- name: "mount filesystem on partition"
  mount:
    name: "{{mount_dir}}"
    src: "{{ disks_path }}{{ vol_name }}1"
    state: mounted
    fstype: xfs
    opts: defaults,pquota
