- name: "Check if docker is installed"
  shell: docker-compose --version
  register: docker
  ignore_errors: true

- name: "Install docker dependencies"
  shell: "{{ item }}"
  with_items:
    - sudo apt update
    - sudo apt upgrade -y
    - sudo apt install -y apt-transport-https ca-certificates curl software-properties-common
    - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -  
    - sudo add-apt-repository -y "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
    - apt-cache policy docker-ce
    - sudo apt install -y docker-ce
    - sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    - sudo chmod +x /usr/local/bin/docker-compose
  when: docker is failed

    
