- name: "Check if nomad certificate exists"
  stat:
   path: "{{ path }}nomad-ca.pem"
  register: stat_ca

- name: "Generate CA certificates"
  shell: cfssl print-defaults csr | cfssl gencert -initca - | cfssljson -bare nomad-ca
  when: not stat_ca.stat.exists

- name: "Increase the default certificate expiration time"
  template:
   src: cfssl.j2
   dest: "{{ path }}cfssl.json"
   owner: ubuntu

- name: "Check if server certificate exists"
  stat:
   path: "{{ path }}server.pem"
  register: stat_server

- name: "Add public host"
  lineinfile:
    path: "{{ hosts }}"
    line: "{{ ansible_host }} {{ inventory_hostname }}" 

- name: "Generate server certificate"
  shell: "echo '{}' | cfssl gencert -ca={{ path }}nomad-ca.pem -ca-key={{ path }}nomad-ca-key.pem -config={{ path }}cfssl.json -hostname=\"{{ inventory_hostname }},server.{{ consul_dc_name }}.nomad,server.{{ consul_dc_name }}.nomad,localhost,127.0.0.1\" - | cfssljson -bare server"
  when: not stat_server.stat.exists

- name: "Check if client certificate exists"
  stat:
   path: "{{ path }}client.pem"
  register: stat_client

- name: "Generate client certificate"
  shell: "echo '{}' | cfssl gencert -ca={{ path }}nomad-ca.pem -ca-key={{ path }}nomad-ca-key.pem -config={{ path }}cfssl.json -hostname=\"{{ inventory_hostname }},client.{{ consul_dc_name }}.nomad,client.{{ consul_dc_name }}.nomad,localhost,127.0.0.1\" - | cfssljson -bare client"
  when: not stat_client.stat.exists

- name: "Check if CLI certificate exists"
  stat:
   path: "{{ path }}cli.pem"
  register: stat_cli

- name: "Generate CLI certificate"
  shell: "echo '{}' | cfssl gencert -ca=nomad-ca.pem -ca-key=nomad-ca-key.pem -profile=client \
- | cfssljson -bare cli"
  when: not stat_cli.stat.exists

- name: "Export nomad addr"
  lineinfile:
    path: "{{ environment_file }}"
    line: "{{ item }}"
  with_items:
    - export NOMAD_ADDR=https://127.0.0.1:4646
    - export NOMAD_CACERT={{ nomad_certs }}nomad-ca.pem
    - export NOMAD_CLIENT_CERT={{ nomad_certs }}cli.pem
    - export NOMAD_CLIENT_KEY={{ nomad_certs }}cli-key.pem

- name: "Set exports"
  become: false
  shell: ". {{ environment_file }}"

- name: "Generate web browser certificate for nomad's UI"
  shell: "openssl pkcs12 -export -inkey ./cli-key.pem -in ./cli.pem -out ./cli.p12 -passout pass:{{ nomad_ui_passwd }} -passin pass:{{ nomad_ui_passwd }}"

- name: "Create zip with nomad's UI certificate"
  community.general.archive:
    path:
      - cli.p12
      - cli.pem
      - cli-key.pem
      - nomad-ca.pem
    dest: "{{ consul_dc_name }}.zip"
    format: zip
