---
# tasks file for nomad_master

- name: Generating nomad certificates

  block:
  - name: "Generate"
    include_tasks: generate_certificates.yml

  - name: "Copy"
    include_tasks: copy_certificates.yml

