- name: "Check if consul ZIP file exists"
  stat:
   path: "{{ path }}consul_{{ consul_version }}_linux_amd64.zip"
  register: stat_consul_zip

- name: "Download Consul binary"
  command: curl --silent --remote-name "https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_amd64.zip"
  when: stat_consul_zip.stat.exists == False

- name: "Unzip consul file"
  command: "{{ item }}"
  with_items:
   - unzip {{ path }}consul_{{ consul_version }}_linux_amd64.zip
   - mv consul {{ path_bin }}
   - "{{ consul }} -autocomplete-install"
   - mkdir --parents {{ consul_certs_dir }}
   - mkdir --parents {{ consul_data_dir }}
   - useradd --system --home {{ consul_config_dir }} --shell /bin/false {{ consul }}

