- name: "Get number of consul servers"
  shell: "consul members | grep server | wc -l"
  register: grep_result

- name: "Set number of consul servers as a variable"
  set_fact:
    num_consul_servers: "{{ grep_result.stdout | int }}"

- name: "Copy server.hcl configuration"
  template:
   src: templates/nomad_server.j2
   dest: "{{ nomad_config }}server.hcl"
   owner: ubuntu


