---
name: CI

on:

  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  nomad_test:
    name: Nomad + Consul Roles Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - rockylinux9
          - ubuntu2204

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4

      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        # Pin version of requests due to an error in docker-py lib
        # https://github.com/docker/docker-py/issues/3256
        run: pip3 install ansible molecule-plugins[docker] docker requests<2.32.0

      - name: Run Molecule tests.
        run: molecule test --all
        working-directory: tests/nomad
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
