- name: "Download Consul binary"
  get_url:
   url: "https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_amd64.zip"
   dest: "{{ path }}consul_{{ consul_version }}_linux_amd64.zip"

- name: "Unzip consul file"
  unarchive:
   src: "{{ path }}consul_{{ consul_version }}_linux_amd64.zip"
   dest: "{{ path_bin }}"
   remote_src: yes
